server {
    listen 80;
    server_name project2.local;
    root /var/www/project2;
    index index.html;

    access_log /var/log/nginx/project2.access.log;
    error_log /var/log/nginx/project2.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
}
